version: '3'
  
services:
    api:
        container_name: api
        build: .
        volumes:
            - .:/code
        depends_on:
            - db
        ports:
            - "5000:5000"
        networks:
            internal_network:
                ipv4_address: 172.25.0.10

        restart: on-failure
        command: ["uwsgi", "--ini", "/code/wsgi.ini"]
    db:
        container_name: database
        image: mariadb:latest
        ports:
            - "3308:3306"
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
            - ~/mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
        restart: always
        networks:
            - internal_network
networks:
    internal_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.25.0.0/16

volumes:
    mysql-data: